# Generated by Django 2.2.5 on 2019-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Picture',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('title', models.CharField(max_length=255)),
        ('artist', models.CharField(max_length=255)),
        ('url', models.CharField(max_length=255)),
      ],
    ),
  ]
